import type { Destination } from "./destinations.ts";

/** Catalog expansion: destinations popular with Canadian travellers, plus regional coverage. */
export const MORE_DESTINATIONS: Destination[] = [
  {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    aliases: ["amsterdam netherlands"],
    airport: "AMS",
    lat: 52.3676,
    lon: 4.9041,
    region: "europe",
    climate: "temperate",
    palette: ["#1e40af", "#f97316"],
    tagline: "Canals, Old Masters and life on two wheels.",
    bestMonths: [4, 5, 6, 9],
    areas: {
      shoestring: { name: "Amsterdam-Oost", why: "Leafy, local and a short tram ride to the centre." },
      comfort: { name: "De Jordaan", why: "Postcard canals, brown cafés and the Nine Streets on your doorstep." },
      luxury: { name: "Canal Belt (Grachtengordel)", why: "Seventeenth-century canal houses turned grand hotels." },
    },
    daily: {
      shoestring: { lodging: 140, food: 45, transport: 10 },
      comfort: { lodging: 260, food: 85, transport: 12 },
      luxury: { lodging: 650, food: 200, transport: 40 },
    },
    flightEst: 750,
    eats: ["Fresh stroopwafels at the Albert Cuyp Market", "Bitterballen with a beer in a brown café", "Indonesian rijsttafel", "Raw herring from a street cart", "Apple pie at Winkel 43"],
    tips: ["Book the Anne Frank House online; tickets release about six weeks ahead.", "Stay out of the red bike lanes when you're on foot.", "Tap a contactless card on trams and metros (check in and out)."],
    activities: [
      { key: "rijks", title: "Rijksmuseum", description: "The Night Watch, Vermeer's Milkmaid and Dutch Golden Age treasures.", cats: ["art", "history", "culture"], slot: "morning", hrs: 3, cost: 25, area: "Museumplein", bookable: true, kids: true },
      { key: "van-gogh", title: "Van Gogh Museum", description: "The world's largest collection of Van Gogh's work.", cats: ["art"], slot: "afternoon", hrs: 2, cost: 22, area: "Museumplein", bookable: true, kids: true },
      { key: "anne-frank", title: "Anne Frank House", description: "The secret annex where Anne Frank wrote her diary.", cats: ["history", "culture"], slot: "morning", hrs: 1.5, cost: 16, area: "Jordaan", tip: "Timed tickets only, sold online.", bookable: true },
      { key: "canal-cruise-ams", title: "Canal cruise", description: "See the UNESCO canal ring from the water.", cats: ["culture", "relaxation"], slot: "evening", hrs: 1.5, cost: 25, area: "Canal Belt", bookable: true, kids: true },
      { key: "jordaan", title: "Jordaan and the Nine Streets", description: "Hidden hofjes, indie shops and canal-side cafés.", cats: ["shopping", "culture"], slot: "afternoon", hrs: 2.5, cost: 0, area: "Jordaan", kids: true },
      { key: "vondelpark", title: "Vondelpark by bike", description: "Rent a bike and ride through the city's favourite park.", cats: ["nature", "adventure", "family"], slot: "morning", hrs: 2, cost: 15, area: "Oud-Zuid", kids: true },
      { key: "foodhallen", title: "Foodhallen", description: "An indoor food market in a converted tram depot.", cats: ["food"], slot: "evening", hrs: 1.5, cost: 25, area: "Oud-West", kids: true },
      { key: "zaanse", title: "Zaanse Schans windmills", description: "Working windmills, clog makers and cheese farms.", cats: ["history", "family"], slot: "morning", hrs: 5, cost: 20, area: "Zaandam", kids: true },
      { key: "ndsm", title: "NDSM Wharf", description: "Free ferry to a shipyard turned street-art and creative hub.", cats: ["art", "nightlife"], slot: "afternoon", hrs: 2.5, cost: 0, area: "Amsterdam-Noord" },
      { key: "brown-cafe", title: "Brown café crawl", description: "Centuries-old pubs with candlelight and jenever.", cats: ["nightlife", "food"], slot: "evening", hrs: 2.5, cost: 35, area: "Jordaan" },
      { key: "nemo", title: "NEMO Science Museum", description: "Hands-on science with a free rooftop view.", cats: ["family"], slot: "afternoon", hrs: 2.5, cost: 20, area: "Oosterdok", bookable: true, kids: true },
      { key: "albert-cuyp", title: "Albert Cuyp Market", description: "Amsterdam's biggest street market.", cats: ["food", "shopping"], slot: "morning", hrs: 1.5, cost: 10, area: "De Pijp", kids: true },
    ],
  },
  {
    slug: "dublin",
    name: "Dublin",
    country: "Ireland",
    aliases: ["dublin ireland"],
    airport: "DUB",
    lat: 53.3498,
    lon: -6.2603,
    region: "europe",
    climate: "temperate",
    palette: ["#166534", "#ca8a04"],
    tagline: "Pubs, poets and the wild Atlantic coast nearby.",
    bestMonths: [5, 6, 7, 8, 9],
    areas: {
      shoestring: { name: "Smithfield", why: "Good-value stays by the Luas tram line." },
      comfort: { name: "Temple Bar edges / St Stephen's Green", why: "Walk to Trinity, Grafton Street and the pubs." },
      luxury: { name: "Ballsbridge", why: "Georgian elegance and quieter five-star hotels." },
    },
    daily: {
      shoestring: { lodging: 130, food: 45, transport: 8 },
      comfort: { lodging: 250, food: 85, transport: 12 },
      luxury: { lodging: 600, food: 190, transport: 40 },
    },
    flightEst: 720,
    eats: ["A pint and a toastie in a traditional pub", "Irish stew", "Fish and chips from Leo Burdock's", "A full Irish breakfast", "Seafood chowder in Howth"],
    tips: ["Book the Book of Kells and the Guinness Storehouse ahead in summer.", "Leap Visitor Cards cover buses, the Luas and DART.", "Pack a rain jacket in every season."],
    activities: [
      { key: "trinity", title: "Trinity College and the Book of Kells", description: "A ninth-century manuscript and the breathtaking Long Room library.", cats: ["history", "culture"], slot: "morning", hrs: 2, cost: 25, area: "City centre", bookable: true, kids: true },
      { key: "guinness", title: "Guinness Storehouse", description: "Brewing history and a pint in the Gravity Bar.", cats: ["food", "culture"], slot: "afternoon", hrs: 2.5, cost: 30, area: "The Liberties", bookable: true },
      { key: "kilmainham", title: "Kilmainham Gaol", description: "A guided tour through Ireland's struggle for independence.", cats: ["history"], slot: "morning", hrs: 1.5, cost: 10, area: "Kilmainham", bookable: true },
      { key: "trad-music", title: "Traditional music session", description: "Live trad music in an old pub.", cats: ["nightlife", "culture"], slot: "evening", hrs: 3, cost: 30, area: "Temple Bar" },
      { key: "howth", title: "Howth cliff walk", description: "DART to a fishing village and its sea-cliff loop.", cats: ["nature", "adventure"], slot: "morning", hrs: 4, cost: 10, area: "Howth", kids: true },
      { key: "epic", title: "EPIC The Irish Emigration Museum", description: "Interactive stories of the Irish diaspora.", cats: ["history", "family"], slot: "afternoon", hrs: 2, cost: 25, area: "Docklands", bookable: true, kids: true },
      { key: "st-stephens", title: "St Stephen's Green and Grafton Street", description: "A Georgian park, buskers and shopping.", cats: ["relaxation", "shopping"], slot: "afternoon", hrs: 2, cost: 0, area: "City centre", kids: true },
      { key: "glendalough", title: "Wicklow Mountains and Glendalough", description: "A monastic valley, lakes and hikes.", cats: ["nature", "history"], slot: "morning", hrs: 8, cost: 45, area: "Wicklow", bookable: true, kids: true },
      { key: "literary-pub", title: "Literary pub crawl", description: "Joyce, Beckett and Wilde, performed by actors.", cats: ["culture", "nightlife"], slot: "evening", hrs: 2.5, cost: 20, area: "City centre", bookable: true },
      { key: "jameson", title: "Jameson Distillery Bow St.", description: "Whiskey tasting in the original distillery.", cats: ["food"], slot: "afternoon", hrs: 1.5, cost: 30, area: "Smithfield", bookable: true },
      { key: "phoenix-park", title: "Phoenix Park", description: "Wild deer and Dublin Zoo in one of Europe's largest parks.", cats: ["nature", "family"], slot: "morning", hrs: 3, cost: 0, area: "Phoenix Park", kids: true },
    ],
  },
  {
    slug: "prague",
    name: "Prague",
    country: "Czechia",
    aliases: ["praha", "prague czech republic"],
    airport: "PRG",
    lat: 50.0755,
    lon: 14.4378,
    region: "europe",
    climate: "temperate",
    palette: ["#7f1d1d", "#d97706"],
    tagline: "Spires, beer halls and a fairy-tale old town.",
    bestMonths: [4, 5, 6, 9, 10, 12],
    areas: {
      shoestring: { name: "Žižkov", why: "Cheap, characterful and full of pubs." },
      comfort: { name: "Malá Strana", why: "Baroque lanes under the castle, walkable to Old Town." },
      luxury: { name: "Old Town (Staré Město)", why: "Palace hotels steps from the Astronomical Clock." },
    },
    daily: {
      shoestring: { lodging: 65, food: 25, transport: 5 },
      comfort: { lodging: 150, food: 50, transport: 8 },
      luxury: { lodging: 450, food: 140, transport: 30 },
    },
    flightEst: 850,
    eats: ["Svíčková (beef in cream sauce) at a beer hall", "Trdelník from a street stand", "Pilsner straight from the tank", "Chlebíčky open sandwiches", "Goulash in a bread bowl"],
    tips: ["Cross Charles Bridge at sunrise to have it nearly to yourself.", "Pay in koruna; decline dynamic currency conversion at card terminals.", "Public transit tickets must be validated before boarding."],
    activities: [
      { key: "castle", title: "Prague Castle and St Vitus Cathedral", description: "The world's largest ancient castle complex.", cats: ["history", "culture"], slot: "morning", hrs: 3.5, cost: 20, area: "Hradčany", bookable: true, kids: true },
      { key: "charles-bridge", title: "Charles Bridge and Old Town Square", description: "Baroque statues, the Astronomical Clock and spires.", cats: ["history", "culture"], slot: "afternoon", hrs: 2.5, cost: 0, area: "Old Town", kids: true },
      { key: "jewish-quarter", title: "Josefov Jewish Quarter", description: "Synagogues and the Old Jewish Cemetery.", cats: ["history"], slot: "morning", hrs: 2.5, cost: 22, area: "Josefov", bookable: true },
      { key: "beer-tour", title: "Czech beer tasting", description: "Unfiltered lagers and pub culture with a local guide.", cats: ["food", "nightlife"], slot: "evening", hrs: 3, cost: 50, area: "New Town", bookable: true },
      { key: "petrin", title: "Petřín Hill", description: "Funicular, a mini Eiffel Tower and a mirror maze.", cats: ["nature", "family"], slot: "afternoon", hrs: 2, cost: 8, area: "Malá Strana", kids: true },
      { key: "vltava", title: "Vltava river cruise", description: "Evening cruise beneath the castle lights.", cats: ["relaxation", "culture"], slot: "evening", hrs: 1.5, cost: 25, area: "Vltava", bookable: true, kids: true },
      { key: "kutna-hora", title: "Kutná Hora day trip", description: "The bone church (Sedlec Ossuary) and a Gothic cathedral.", cats: ["history"], slot: "morning", hrs: 7, cost: 40, area: "Kutná Hora", bookable: true },
      { key: "vysehrad", title: "Vyšehrad fortress", description: "Clifftop ramparts and a cemetery of Czech greats.", cats: ["history", "nature"], slot: "afternoon", hrs: 2, cost: 0, area: "Vyšehrad", kids: true },
      { key: "black-light", title: "Black-light theatre", description: "Prague's uniquely visual theatre tradition.", cats: ["culture", "family"], slot: "evening", hrs: 1.5, cost: 30, area: "Old Town", bookable: true, kids: true },
      { key: "letna", title: "Letná beer garden", description: "Views over the bridges with a cheap pint.", cats: ["relaxation", "nightlife"], slot: "evening", hrs: 2, cost: 10, area: "Letná" },
      { key: "mucha", title: "Mucha Museum", description: "Art Nouveau posters by Alphonse Mucha.", cats: ["art"], slot: "afternoon", hrs: 1, cost: 12, area: "New Town" },
    ],
  },
  {
    slug: "florence",
    name: "Florence",
    country: "Italy",
    aliases: ["firenze", "florence italy"],
    airport: "FLR",
    lat: 43.7696,
    lon: 11.2558,
    region: "europe",
    climate: "mediterranean",
    palette: ["#9a3412", "#65a30d"],
    tagline: "The Renaissance, Tuscan wine and bistecca.",
    bestMonths: [4, 5, 6, 9, 10],
    areas: {
      shoestring: { name: "San Lorenzo / Santa Maria Novella", why: "Near the station and the Mercato Centrale." },
      comfort: { name: "Santa Croce", why: "Central, lively evenings and artisan workshops." },
      luxury: { name: "Oltrarno", why: "Palazzo hotels across the river, quieter and artisanal." },
    },
    daily: {
      shoestring: { lodging: 100, food: 40, transport: 4 },
      comfort: { lodging: 220, food: 80, transport: 6 },
      luxury: { lodging: 650, food: 200, transport: 35 },
    },
    flightEst: 900,
    eats: ["Bistecca alla fiorentina", "Lampredotto sandwich from a street cart", "Schiacciata from All'Antico Vinaio", "Gelato from a gelateria artigianale", "Ribollita soup"],
    tips: ["Book the Uffizi and the Accademia (David) well ahead.", "Florence is compact; walk everywhere and skip taxis.", "Many restaurants close between lunch and dinner service."],
    activities: [
      { key: "uffizi", title: "Uffizi Gallery", description: "Botticelli's Birth of Venus and the Renaissance in one building.", cats: ["art", "history"], slot: "morning", hrs: 3, cost: 30, area: "Piazza della Signoria", bookable: true },
      { key: "david", title: "Accademia: Michelangelo's David", description: "See the original David up close.", cats: ["art"], slot: "afternoon", hrs: 1.5, cost: 25, area: "San Marco", bookable: true, kids: true },
      { key: "duomo", title: "Duomo dome climb", description: "Climb 463 steps inside Brunelleschi's dome.", cats: ["history", "adventure", "culture"], slot: "morning", hrs: 2.5, cost: 35, area: "Duomo", bookable: true, kids: true },
      { key: "chianti", title: "Chianti wine day trip", description: "Hill towns, vineyards and a long Tuscan lunch.", cats: ["food", "nature"], slot: "morning", hrs: 8, cost: 120, area: "Chianti", bookable: true },
      { key: "piazzale", title: "Sunset at Piazzale Michelangelo", description: "The classic view over the Arno.", cats: ["relaxation", "culture"], slot: "evening", hrs: 1.5, cost: 0, area: "Oltrarno", kids: true },
      { key: "mercato-centrale", title: "Mercato Centrale", description: "A food market with a modern food hall upstairs.", cats: ["food"], slot: "morning", hrs: 1.5, cost: 20, area: "San Lorenzo", kids: true },
      { key: "boboli", title: "Pitti Palace and Boboli Gardens", description: "Medici palace and Renaissance gardens.", cats: ["history", "nature"], slot: "afternoon", hrs: 3, cost: 22, area: "Oltrarno", bookable: true, kids: true },
      { key: "oltrarno-artisans", title: "Oltrarno artisan workshops", description: "Leather, paper and goldsmiths at work.", cats: ["shopping", "art"], slot: "afternoon", hrs: 2, cost: 0, area: "Oltrarno" },
      { key: "cooking-fl", title: "Tuscan cooking class", description: "Fresh pasta and tiramisù with a Florentine chef.", cats: ["food", "family"], slot: "evening", hrs: 3, cost: 90, area: "Santa Croce", bookable: true, kids: true },
      { key: "pisa-siena", title: "Siena and San Gimignano day trip", description: "Medieval towers and Siena's shell-shaped Campo.", cats: ["history", "culture"], slot: "morning", hrs: 9, cost: 80, area: "Tuscany", bookable: true },
      { key: "wine-bar", title: "Enoteca wine-bar evening", description: "Tuscan reds and crostini in Santo Spirito.", cats: ["nightlife", "food"], slot: "evening", hrs: 2, cost: 35, area: "Santo Spirito" },
    ],
  },
  {
    slug: "athens",
    name: "Athens",
    country: "Greece",
    aliases: ["athina", "athens greece"],
    airport: "ATH",
    lat: 37.9838,
    lon: 23.7275,
    region: "europe",
    climate: "mediterranean",
    palette: ["#1d4ed8", "#e2e8f0"],
    tagline: "The Acropolis, rooftop sunsets and ferries to the islands.",
    bestMonths: [4, 5, 6, 9, 10],
    areas: {
      shoestring: { name: "Psyrri", why: "Lively, central and budget-friendly." },
      comfort: { name: "Plaka / Koukaki", why: "Under the Acropolis, walkable to the main sights." },
      luxury: { name: "Syntagma / Kolonaki", why: "Upscale hotels with Acropolis-view rooftops." },
    },
    daily: {
      shoestring: { lodging: 70, food: 30, transport: 5 },
      comfort: { lodging: 160, food: 60, transport: 10 },
      luxury: { lodging: 480, food: 150, transport: 40 },
    },
    flightEst: 950,
    eats: ["Souvlaki in Monastiraki", "Loukoumades (honey doughnuts)", "Meze and ouzo in Psyrri", "Fresh fish in Piraeus", "Spanakopita from a bakery"],
    tips: ["Visit the Acropolis at opening or late afternoon to avoid the heat and crowds.", "A combined ticket covers several ancient sites.", "Most museums and sites close earlier in winter."],
    activities: [
      { key: "acropolis", title: "Acropolis and Parthenon", description: "Fifth-century BC temples above the city.", cats: ["history", "culture"], slot: "morning", hrs: 3, cost: 32, area: "Acropolis", tip: "Timed entry; book the 8am slot.", bookable: true, kids: true },
      { key: "acropolis-museum", title: "Acropolis Museum", description: "The site's original sculptures over excavated ruins.", cats: ["history", "art"], slot: "afternoon", hrs: 2, cost: 22, area: "Makrygianni", bookable: true, kids: true },
      { key: "agora", title: "Ancient Agora", description: "Where Socrates walked, with the Temple of Hephaestus.", cats: ["history"], slot: "morning", hrs: 2, cost: 22, area: "Monastiraki", kids: true },
      { key: "plaka", title: "Plaka and Anafiotika", description: "Whitewashed island-style lanes under the Acropolis.", cats: ["culture", "shopping"], slot: "afternoon", hrs: 2, cost: 0, area: "Plaka", kids: true },
      { key: "rooftop-ath", title: "Rooftop sunset over the Acropolis", description: "Cocktails as the Parthenon lights up.", cats: ["nightlife", "relaxation"], slot: "evening", hrs: 2, cost: 30, area: "Monastiraki" },
      { key: "sounion", title: "Cape Sounion sunset", description: "The Temple of Poseidon on a sea cliff.", cats: ["history", "nature"], slot: "afternoon", hrs: 5, cost: 50, area: "Sounion", bookable: true, kids: true },
      { key: "aegina", title: "Island day trip to Aegina", description: "Ferry to pistachio groves and beaches.", cats: ["relaxation", "nature"], slot: "morning", hrs: 8, cost: 35, area: "Saronic Gulf", kids: true },
      { key: "food-tour-ath", title: "Athens food tour", description: "Central Market, koulouri and meze.", cats: ["food"], slot: "morning", hrs: 3.5, cost: 80, area: "Central Market", bookable: true },
      { key: "lycabettus", title: "Mount Lycabettus", description: "The highest viewpoint in Athens.", cats: ["nature"], slot: "evening", hrs: 2, cost: 10, area: "Kolonaki", kids: true },
      { key: "national-arch", title: "National Archaeological Museum", description: "Mycenaean gold and the Antikythera mechanism.", cats: ["history", "art"], slot: "afternoon", hrs: 2.5, cost: 14, area: "Exarchia" },
      { key: "psyrri-night", title: "Psyrri tavernas and live music", description: "Rebetiko and late tavernas.", cats: ["nightlife", "food"], slot: "evening", hrs: 3, cost: 35, area: "Psyrri" },
    ],
  },
  {
    slug: "istanbul",
    name: "Istanbul",
    country: "Türkiye",
    aliases: ["istanbul turkey", "constantinople"],
    airport: "IST",
    lat: 41.0082,
    lon: 28.9784,
    region: "middle-east",
    climate: "mediterranean",
    palette: ["#9f1239", "#0e7490"],
    tagline: "Two continents, a thousand domes and the Bosphorus.",
    bestMonths: [4, 5, 9, 10, 11],
    areas: {
      shoestring: { name: "Kadıköy (Asian side)", why: "Foodie neighbourhood with ferries to the old city." },
      comfort: { name: "Sultanahmet", why: "Walk to Hagia Sophia, the Blue Mosque and the bazaar." },
      luxury: { name: "Beşiktaş / Bosphorus shore", why: "Palace hotels on the water." },
    },
    daily: {
      shoestring: { lodging: 55, food: 25, transport: 5 },
      comfort: { lodging: 150, food: 55, transport: 10 },
      luxury: { lodging: 500, food: 150, transport: 40 },
    },
    flightEst: 1000,
    eats: ["Simit and çay on the go", "Balık ekmek (fish sandwich) at Eminönü", "Mezes and rakı in Beyoğlu", "Baklava from Karaköy Güllüoğlu", "Kebab in Kadıköy"],
    tips: ["Use an Istanbulkart for trams, metro and ferries.", "Mosques close to visitors at prayer times; dress modestly and carry a scarf.", "Ferries are the cheapest Bosphorus cruise."],
    activities: [
      { key: "hagia-sophia", title: "Hagia Sophia", description: "Fifteen centuries of empire under one dome.", cats: ["history", "culture"], slot: "morning", hrs: 1.5, cost: 25, area: "Sultanahmet", kids: true },
      { key: "blue-mosque", title: "Blue Mosque and Hippodrome", description: "Iznik tiles and Roman-era monuments.", cats: ["history", "culture"], slot: "morning", hrs: 1.5, cost: 0, area: "Sultanahmet", kids: true },
      { key: "topkapi", title: "Topkapı Palace", description: "The Ottoman sultans' palace and harem.", cats: ["history"], slot: "afternoon", hrs: 3, cost: 45, area: "Sultanahmet", bookable: true, kids: true },
      { key: "grand-bazaar", title: "Grand Bazaar and Spice Bazaar", description: "4,000 shops of carpets, lamps and spices.", cats: ["shopping", "food"], slot: "afternoon", hrs: 3, cost: 0, area: "Beyazıt", kids: true },
      { key: "bosphorus", title: "Bosphorus cruise", description: "Palaces and wooden mansions between Europe and Asia.", cats: ["relaxation", "culture"], slot: "afternoon", hrs: 2, cost: 20, area: "Eminönü", bookable: true, kids: true },
      { key: "basilica-cistern", title: "Basilica Cistern", description: "A sunken Byzantine palace of columns.", cats: ["history"], slot: "morning", hrs: 1, cost: 30, area: "Sultanahmet", bookable: true, kids: true },
      { key: "hammam-ist", title: "Historic hammam", description: "A centuries-old Turkish bath.", cats: ["relaxation"], slot: "evening", hrs: 2, cost: 80, area: "Cağaloğlu", bookable: true },
      { key: "kadikoy", title: "Kadıköy food crawl", description: "Ferry to Asia for the city's best market streets.", cats: ["food"], slot: "evening", hrs: 3, cost: 45, area: "Kadıköy", bookable: true },
      { key: "galata", title: "Galata Tower and Karaköy", description: "Panoramic views, then cafés below.", cats: ["culture"], slot: "evening", hrs: 2, cost: 30, area: "Beyoğlu", kids: true },
      { key: "balat", title: "Balat and Fener", description: "Colourful houses, churches and antique shops.", cats: ["culture", "art"], slot: "morning", hrs: 2.5, cost: 0, area: "Balat" },
      { key: "istiklal", title: "İstiklal Avenue nightlife", description: "Meyhanes and rooftop bars off Taksim.", cats: ["nightlife"], slot: "evening", hrs: 3, cost: 40, area: "Beyoğlu" },
    ],
  },
  {
    slug: "seoul",
    name: "Seoul",
    country: "South Korea",
    aliases: ["seoul korea", "seoul south korea"],
    airport: "SEL",
    lat: 37.5665,
    lon: 126.978,
    region: "east-asia",
    climate: "temperate",
    palette: ["#4338ca", "#db2777"],
    tagline: "Palaces, K-culture and barbecue at midnight.",
    bestMonths: [4, 5, 9, 10, 11],
    areas: {
      shoestring: { name: "Hongdae", why: "Youthful, cheap stays and endless nightlife." },
      comfort: { name: "Myeongdong / Jongno", why: "Central for palaces, markets and transit." },
      luxury: { name: "Gangnam", why: "Sleek hotels, design stores and fine dining." },
    },
    daily: {
      shoestring: { lodging: 60, food: 30, transport: 6 },
      comfort: { lodging: 150, food: 60, transport: 10 },
      luxury: { lodging: 450, food: 160, transport: 40 },
    },
    flightEst: 1150,
    eats: ["Korean barbecue (samgyeopsal)", "Street food at Gwangjang Market", "Fried chicken and beer (chimaek)", "Bibimbap", "Hotteok sweet pancakes"],
    tips: ["Naver Map and KakaoMap work far better than Google Maps here.", "A T-money card covers subway, buses and convenience stores.", "Wearing hanbok gets you free palace entry."],
    activities: [
      { key: "gyeongbok", title: "Gyeongbokgung Palace", description: "The grand Joseon palace and changing of the guard.", cats: ["history", "culture"], slot: "morning", hrs: 2.5, cost: 3, area: "Jongno", kids: true },
      { key: "bukchon", title: "Bukchon Hanok Village", description: "Traditional hanok houses on hillside lanes.", cats: ["culture", "history"], slot: "afternoon", hrs: 2, cost: 0, area: "Jongno", kids: true },
      { key: "gwangjang", title: "Gwangjang Market", description: "Mung-bean pancakes and bibimbap at market stalls.", cats: ["food"], slot: "evening", hrs: 2, cost: 20, area: "Jongno", kids: true },
      { key: "n-tower", title: "N Seoul Tower", description: "Cable car to the city's highest viewpoint.", cats: ["culture", "family"], slot: "evening", hrs: 2, cost: 20, area: "Namsan", bookable: true, kids: true },
      { key: "dmz", title: "DMZ tour", description: "Tunnels and observatories on the North Korean border.", cats: ["history", "adventure"], slot: "morning", hrs: 8, cost: 90, area: "Paju", tip: "Bring your passport.", bookable: true },
      { key: "hongdae-night", title: "Hongdae nightlife", description: "Buskers, clubs and noraebang (karaoke).", cats: ["nightlife"], slot: "evening", hrs: 3, cost: 40, area: "Hongdae" },
      { key: "ddp", title: "Dongdaemun Design Plaza", description: "Zaha Hadid's futuristic landmark and night markets.", cats: ["art", "shopping"], slot: "afternoon", hrs: 2, cost: 0, area: "Dongdaemun", kids: true },
      { key: "bukhansan", title: "Hike Bukhansan", description: "Granite peaks inside the city limits.", cats: ["nature", "adventure"], slot: "morning", hrs: 5, cost: 0, area: "Bukhansan" },
      { key: "jjimjilbang", title: "Jjimjilbang spa", description: "Korean bathhouse with saunas and hot pools.", cats: ["relaxation"], slot: "evening", hrs: 3, cost: 15, area: "Yongsan" },
      { key: "myeongdong", title: "Myeongdong shopping and street food", description: "K-beauty and snacks.", cats: ["shopping", "food"], slot: "afternoon", hrs: 2.5, cost: 15, area: "Myeongdong", kids: true },
      { key: "lotte-world", title: "Lotte World", description: "One of the world's largest indoor theme parks.", cats: ["family"], slot: "morning", hrs: 5, cost: 50, area: "Jamsil", bookable: true, kids: true },
      { key: "korean-cooking", title: "Kimchi and Korean cooking class", description: "Hands-on kimchi and bulgogi.", cats: ["food", "family"], slot: "afternoon", hrs: 3, cost: 60, area: "Jongno", bookable: true, kids: true },
    ],
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    aliases: ["singapore city"],
    airport: "SIN",
    lat: 1.3521,
    lon: 103.8198,
    region: "southeast-asia",
    climate: "tropical",
    palette: ["#be123c", "#059669"],
    tagline: "Hawker feasts, supertrees and a garden city.",
    bestMonths: [2, 3, 4, 7, 8],
    areas: {
      shoestring: { name: "Little India / Kampong Glam", why: "Colourful and the best-value stays." },
      comfort: { name: "Clarke Quay / Chinatown", why: "Central, with river walks and hawker food." },
      luxury: { name: "Marina Bay", why: "Skyline hotels and rooftop pools." },
    },
    daily: {
      shoestring: { lodging: 110, food: 25, transport: 8 },
      comfort: { lodging: 260, food: 55, transport: 12 },
      luxury: { lodging: 600, food: 160, transport: 40 },
    },
    flightEst: 1400,
    eats: ["Hainanese chicken rice at Maxwell Food Centre", "Chilli crab", "Laksa", "Satay at Lau Pa Sat", "Kaya toast and kopi for breakfast"],
    tips: ["Tap a contactless card on the MRT and buses.", "Carry an umbrella because afternoon storms are common.", "Chewing gum sales are banned, and littering fines are steep."],
    activities: [
      { key: "gardens-bay", title: "Gardens by the Bay", description: "Supertrees, the Cloud Forest and the Flower Dome.", cats: ["nature", "family"], slot: "afternoon", hrs: 3, cost: 35, area: "Marina Bay", bookable: true, kids: true },
      { key: "garden-rhapsody", title: "Garden Rhapsody light show", description: "Free evening light show at the Supertree Grove.", cats: ["culture", "family"], slot: "evening", hrs: 1, cost: 0, area: "Marina Bay", kids: true },
      { key: "hawker", title: "Hawker centre feast", description: "Michelin-listed food stalls for a few dollars.", cats: ["food"], slot: "evening", hrs: 1.5, cost: 15, area: "Chinatown", kids: true },
      { key: "zoo", title: "Singapore Zoo or Night Safari", description: "Open-concept zoo in the rainforest.", cats: ["family", "nature"], slot: "morning", hrs: 4, cost: 45, area: "Mandai", bookable: true, kids: true },
      { key: "chinatown-sg", title: "Chinatown and Buddha Tooth Relic Temple", description: "Heritage shophouses and temples.", cats: ["culture", "history"], slot: "morning", hrs: 2.5, cost: 0, area: "Chinatown", kids: true },
      { key: "kampong-glam", title: "Kampong Glam and Haji Lane", description: "The Sultan Mosque and indie boutiques.", cats: ["shopping", "culture"], slot: "afternoon", hrs: 2.5, cost: 0, area: "Kampong Glam" },
      { key: "sentosa", title: "Sentosa island", description: "Beaches, Universal Studios and the S.E.A. Aquarium.", cats: ["family", "relaxation"], slot: "morning", hrs: 6, cost: 80, area: "Sentosa", bookable: true, kids: true },
      { key: "macritchie", title: "MacRitchie treetop walk", description: "A suspension bridge through rainforest canopy.", cats: ["nature", "adventure"], slot: "morning", hrs: 4, cost: 0, area: "Central Catchment" },
      { key: "national-gallery-sg", title: "National Gallery Singapore", description: "Southeast Asian art in the old Supreme Court.", cats: ["art", "history"], slot: "afternoon", hrs: 2.5, cost: 20, area: "Civic District" },
      { key: "rooftop-sg", title: "Rooftop bar at Marina Bay", description: "Skyline cocktails with a view of the bay.", cats: ["nightlife"], slot: "evening", hrs: 2, cost: 40, area: "Marina Bay" },
      { key: "little-india", title: "Little India", description: "Sri Veeramakaliamman Temple and Tekka Centre.", cats: ["culture", "food"], slot: "morning", hrs: 2, cost: 10, area: "Little India", kids: true },
    ],
  },
  {
    slug: "cancun",
    name: "Cancún",
    country: "Mexico",
    aliases: ["cancun", "riviera maya", "cancun mexico", "playa del carmen", "tulum"],
    airport: "CUN",
    lat: 21.1619,
    lon: -86.8515,
    region: "latin-america",
    climate: "tropical",
    palette: ["#0891b2", "#f59e0b"],
    tagline: "Turquoise water, cenotes and Maya ruins.",
    bestMonths: [12, 1, 2, 3, 4],
    areas: {
      shoestring: { name: "Downtown Cancún (El Centro)", why: "Local taquerías and budget hotels, with buses to the beaches." },
      comfort: { name: "Playa del Carmen", why: "A walkable beach town midway down the Riviera Maya." },
      luxury: { name: "Cancún Hotel Zone", why: "All-inclusive resorts on the best beaches." },
    },
    daily: {
      shoestring: { lodging: 70, food: 25, transport: 8 },
      comfort: { lodging: 200, food: 60, transport: 20 },
      luxury: { lodging: 550, food: 150, transport: 50 },
    },
    flightEst: 520,
    eats: ["Tacos de cochinita pibil", "Fresh ceviche on the beach", "Marquesitas (crispy crêpes)", "Sopa de lima", "Mezcal and fish tacos in Playa del Carmen"],
    tips: ["Sargassum seaweed varies by season; check beach reports.", "Use reef-safe sunscreen, which is required at cenotes and parks.", "ADO buses are a comfortable, cheap way along the coast."],
    activities: [
      { key: "chichen-itza", title: "Chichén Itzá", description: "The great pyramid of El Castillo, a New Wonder of the World.", cats: ["history", "culture"], slot: "morning", hrs: 10, cost: 110, area: "Yucatán", tip: "Leave early to beat the heat and the tour buses.", bookable: true, kids: true },
      { key: "cenotes", title: "Cenote swim", description: "Crystal-clear limestone sinkholes.", cats: ["nature", "adventure"], slot: "morning", hrs: 4, cost: 40, area: "Ruta de los Cenotes", bookable: true, kids: true },
      { key: "tulum-ruins", title: "Tulum ruins", description: "A Maya port town on a Caribbean cliff.", cats: ["history", "relaxation"], slot: "morning", hrs: 6, cost: 60, area: "Tulum", bookable: true, kids: true },
      { key: "isla-mujeres", title: "Isla Mujeres day trip", description: "Ferry to Playa Norte and golf-cart island hopping.", cats: ["relaxation", "family"], slot: "morning", hrs: 7, cost: 50, area: "Isla Mujeres", kids: true },
      { key: "snorkel", title: "Snorkel the MUSA underwater museum", description: "Sculptures on the reef.", cats: ["adventure", "art"], slot: "afternoon", hrs: 3, cost: 70, area: "Hotel Zone", bookable: true, kids: true },
      { key: "beach-day", title: "Beach day at Playa Delfines", description: "Wide white sand and the Cancún sign.", cats: ["relaxation", "family"], slot: "afternoon", hrs: 3, cost: 0, area: "Hotel Zone", kids: true },
      { key: "xcaret", title: "Xcaret park", description: "Underground rivers, wildlife and an evening show.", cats: ["family", "culture"], slot: "morning", hrs: 9, cost: 130, area: "Playa del Carmen", bookable: true, kids: true },
      { key: "quinta", title: "La Quinta Avenida, Playa del Carmen", description: "Pedestrian strip of shops, bars and cafés.", cats: ["shopping", "nightlife"], slot: "evening", hrs: 3, cost: 30, area: "Playa del Carmen" },
      { key: "parque-palapas", title: "Parque de las Palapas street food", description: "Downtown's evening food stalls and families.", cats: ["food", "family"], slot: "evening", hrs: 2, cost: 12, area: "El Centro", kids: true },
      { key: "catamaran-cun", title: "Catamaran sunset sail", description: "Open bar and snorkel stops.", cats: ["relaxation", "nightlife"], slot: "evening", hrs: 3, cost: 75, area: "Hotel Zone", bookable: true },
      { key: "coco-bongo", title: "Coco Bongo show", description: "Cancún's famous club-meets-cabaret.", cats: ["nightlife"], slot: "evening", hrs: 4, cost: 90, area: "Hotel Zone", bookable: true },
    ],
  },
  {
    slug: "vancouver",
    name: "Vancouver",
    country: "Canada",
    aliases: ["vancouver bc", "vancouver canada"],
    airport: "YVR",
    lat: 49.2827,
    lon: -123.1207,
    region: "north-america",
    climate: "temperate",
    palette: ["#065f46", "#0284c7"],
    tagline: "Mountains, ocean and dim sum within one day.",
    bestMonths: [5, 6, 7, 8, 9],
    areas: {
      shoestring: { name: "Mount Pleasant", why: "Breweries, cafés and fair prices on Main Street." },
      comfort: { name: "Downtown / Yaletown", why: "Walk to the seawall, Stanley Park and Gastown." },
      luxury: { name: "Coal Harbour", why: "Waterfront hotels with mountain views." },
    },
    daily: {
      shoestring: { lodging: 140, food: 45, transport: 8 },
      comfort: { lodging: 260, food: 85, transport: 12 },
      luxury: { lodging: 600, food: 190, transport: 40 },
    },
    flightEst: 400,
    eats: ["Dim sum in Richmond", "Japadog from a street cart", "Sushi (Vancouver's is world-class)", "Granville Island Public Market", "Spot prawns in season (May–June)"],
    tips: ["Compass Card or contactless works across SkyTrain, buses and SeaBus.", "Layers are essential; mountain weather changes quickly.", "Book Grouse Mountain and the Capilano bridge early in summer."],
    activities: [
      { key: "stanley-park", title: "Stanley Park seawall by bike", description: "A 10 km ride past totem poles and beaches.", cats: ["nature", "adventure", "family"], slot: "morning", hrs: 3, cost: 25, area: "Stanley Park", kids: true },
      { key: "granville", title: "Granville Island", description: "Public market, artisan studios and the Aquabus.", cats: ["food", "shopping"], slot: "afternoon", hrs: 2.5, cost: 20, area: "Granville Island", kids: true },
      { key: "capilano", title: "Capilano Suspension Bridge", description: "A canyon bridge plus cliffwalk and treetop walks.", cats: ["nature", "adventure", "family"], slot: "morning", hrs: 3, cost: 60, area: "North Vancouver", bookable: true, kids: true },
      { key: "grouse", title: "Grouse Mountain", description: "Skyride gondola, grizzly refuge and the Grouse Grind.", cats: ["nature", "adventure"], slot: "afternoon", hrs: 4, cost: 70, area: "North Vancouver", bookable: true, kids: true },
      { key: "gastown", title: "Gastown and Chinatown", description: "Steam clock, cobblestones and the Sun Yat-Sen garden.", cats: ["history", "culture"], slot: "afternoon", hrs: 2.5, cost: 15, area: "Gastown", kids: true },
      { key: "moa", title: "Museum of Anthropology at UBC", description: "Northwest Coast First Nations art in a landmark building.", cats: ["art", "history", "culture"], slot: "morning", hrs: 2.5, cost: 25, area: "UBC", bookable: true, kids: true },
      { key: "whistler", title: "Sea-to-Sky to Whistler", description: "Coastal highway to Shannon Falls and the Peak 2 Peak gondola.", cats: ["nature", "adventure"], slot: "morning", hrs: 10, cost: 120, area: "Whistler", bookable: true, kids: true },
      { key: "english-bay", title: "English Bay sunset", description: "Beach sunset at the city's favourite bay.", cats: ["relaxation"], slot: "evening", hrs: 1.5, cost: 0, area: "West End", kids: true },
      { key: "brewery", title: "Brewery Creek tasting crawl", description: "Craft breweries in Mount Pleasant.", cats: ["nightlife", "food"], slot: "evening", hrs: 3, cost: 40, area: "Mount Pleasant" },
      { key: "kayak-van", title: "Kayak Deep Cove", description: "Paddle a fjord-like inlet.", cats: ["adventure", "nature"], slot: "morning", hrs: 3, cost: 60, area: "North Vancouver", bookable: true },
      { key: "richmond-night", title: "Richmond Night Market", description: "Summer weekend Asian street food extravaganza.", cats: ["food", "family", "nightlife"], slot: "evening", hrs: 2.5, cost: 25, area: "Richmond", tip: "Runs weekends from spring to early autumn.", kids: true },
      { key: "aquarium-van", title: "Vancouver Aquarium", description: "Sea otters, sea lions and an Amazon rainforest gallery.", cats: ["family", "nature"], slot: "afternoon", hrs: 2.5, cost: 45, area: "Stanley Park", bookable: true, kids: true },
    ],
  },
  {
    slug: "montreal",
    name: "Montréal",
    country: "Canada",
    aliases: ["montreal", "montreal quebec", "montréal québec"],
    airport: "YUL",
    lat: 45.5019,
    lon: -73.5674,
    region: "north-america",
    climate: "temperate",
    palette: ["#1e3a8a", "#dc2626"],
    tagline: "Bagels, festivals and a European soul in North America.",
    bestMonths: [5, 6, 7, 8, 9, 10],
    areas: {
      shoestring: { name: "Quartier Latin", why: "Budget hotels on the metro, close to Old Montréal." },
      comfort: { name: "Plateau Mont-Royal", why: "Colourful staircases, cafés and the best food streets." },
      luxury: { name: "Old Montréal (Vieux-Montréal)", why: "Boutique hotels in stone buildings by the port." },
    },
    daily: {
      shoestring: { lodging: 110, food: 40, transport: 8 },
      comfort: { lodging: 220, food: 80, transport: 10 },
      luxury: { lodging: 500, food: 180, transport: 35 },
    },
    flightEst: 380,
    eats: ["Smoked meat at Schwartz's", "Wood-fired bagels from St-Viateur or Fairmount", "Poutine at La Banquise", "Jean-Talon Market produce", "Maple taffy in season"],
    tips: ["Summer is festival season (Jazz Fest, Just for Laughs, Francos).", "The underground RÉSO keeps you warm in winter.", "A little French ('bonjour') goes a long way."],
    activities: [
      { key: "old-montreal", title: "Old Montréal and Notre-Dame Basilica", description: "Cobblestones, the Old Port and a dazzling Gothic Revival interior.", cats: ["history", "culture"], slot: "morning", hrs: 3, cost: 15, area: "Vieux-Montréal", bookable: true, kids: true },
      { key: "mont-royal", title: "Mount Royal lookout", description: "Hike to the Kondiaronk Belvedere for skyline views.", cats: ["nature"], slot: "afternoon", hrs: 2.5, cost: 0, area: "Mont-Royal", kids: true },
      { key: "jean-talon", title: "Jean-Talon Market", description: "Québec cheese, maple everything and seasonal produce.", cats: ["food"], slot: "morning", hrs: 2, cost: 20, area: "Little Italy", kids: true },
      { key: "mbam", title: "Montréal Museum of Fine Arts", description: "Québec and Canadian art plus major touring shows.", cats: ["art"], slot: "afternoon", hrs: 2.5, cost: 25, area: "Golden Square Mile", kids: true },
      { key: "plateau-walk", title: "Plateau and Mile End stroll", description: "Murals, spiral staircases and bagel shops.", cats: ["culture", "art", "food"], slot: "afternoon", hrs: 3, cost: 10, area: "Plateau Mont-Royal", kids: true },
      { key: "biodome", title: "Biodôme and Botanical Garden", description: "Four ecosystems under one roof, plus the Chinese Garden.", cats: ["family", "nature"], slot: "morning", hrs: 4, cost: 30, area: "Olympic Park", bookable: true, kids: true },
      { key: "bota-bota", title: "Bota Bota spa-sur-l'eau", description: "A floating Nordic spa on a converted ferry.", cats: ["relaxation"], slot: "afternoon", hrs: 3, cost: 70, area: "Old Port", bookable: true },
      { key: "mtl-food-tour", title: "Montréal food tour", description: "Smoked meat, bagels and poutine with a guide.", cats: ["food", "history"], slot: "afternoon", hrs: 3, cost: 85, area: "Plateau Mont-Royal", bookable: true },
      { key: "st-laurent", title: "Boulevard Saint-Laurent nightlife", description: "Cocktail bars and live music on The Main.", cats: ["nightlife"], slot: "evening", hrs: 3, cost: 40, area: "Plateau Mont-Royal" },
      { key: "aura", title: "AURA at Notre-Dame", description: "An immersive light-and-sound show inside the basilica.", cats: ["culture", "art"], slot: "evening", hrs: 1, cost: 35, area: "Vieux-Montréal", bookable: true, kids: true },
      { key: "lachine", title: "Lachine Canal bike ride", description: "Waterfront cycling to Atwater Market.", cats: ["adventure", "nature", "family"], slot: "morning", hrs: 3, cost: 15, area: "Saint-Henri", kids: true },
      { key: "mont-tremblant", title: "Mont-Tremblant day trip", description: "Laurentian mountains, a gondola and a pedestrian village.", cats: ["nature", "adventure"], slot: "morning", hrs: 9, cost: 70, area: "Laurentians", kids: true },
    ],
  },
  {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    aliases: ["sydney australia"],
    airport: "SYD",
    lat: -33.8688,
    lon: 151.2093,
    region: "oceania",
    climate: "subtropical",
    palette: ["#0369a1", "#f97316"],
    tagline: "Harbour icons, surf beaches and brunch culture.",
    bestMonths: [10, 11, 12, 1, 2, 3, 4],
    areas: {
      shoestring: { name: "Surry Hills", why: "Cafés and pubs with good transport links." },
      comfort: { name: "The Rocks / Circular Quay", why: "Steps from the Opera House and harbour ferries." },
      luxury: { name: "Bondi Beach", why: "Beachfront stays and ocean pools." },
    },
    daily: {
      shoestring: { lodging: 130, food: 45, transport: 12 },
      comfort: { lodging: 260, food: 85, transport: 15 },
      luxury: { lodging: 650, food: 200, transport: 45 },
    },
    flightEst: 1600,
    eats: ["Flat white and smashed avo brunch", "Fish and chips at Manly", "Modern Australian tasting menu", "Barbecue prawns at the Sydney Fish Market", "Meat pie at Harry's Café de Wheels"],
    tips: ["Opal card or contactless covers trains, buses and ferries, with a daily cap.", "Swim between the red and yellow flags.", "The sun is fierce, so slip, slop, slap."],
    activities: [
      { key: "opera-house", title: "Sydney Opera House tour", description: "Behind the sails of an architectural icon.", cats: ["culture", "art"], slot: "morning", hrs: 1.5, cost: 30, area: "Circular Quay", bookable: true, kids: true },
      { key: "bondi-coogee", title: "Bondi to Coogee coastal walk", description: "6 km of cliffs, ocean pools and beaches.", cats: ["nature", "adventure"], slot: "morning", hrs: 3, cost: 0, area: "Bondi", kids: true },
      { key: "manly-ferry", title: "Ferry to Manly", description: "The best-value harbour cruise, then a beach town.", cats: ["relaxation", "family"], slot: "afternoon", hrs: 4, cost: 10, area: "Manly", kids: true },
      { key: "bridge-climb", title: "Sydney Harbour BridgeClimb", description: "Climb the arch for 360° harbour views.", cats: ["adventure"], slot: "evening", hrs: 3.5, cost: 220, area: "The Rocks", bookable: true },
      { key: "rocks-walk", title: "The Rocks historic quarter", description: "Convict-era laneways and weekend markets.", cats: ["history", "shopping"], slot: "afternoon", hrs: 2, cost: 0, area: "The Rocks", kids: true },
      { key: "blue-mountains", title: "Blue Mountains day trip", description: "The Three Sisters, rainforest trails and Scenic World.", cats: ["nature", "adventure"], slot: "morning", hrs: 9, cost: 90, area: "Blue Mountains", bookable: true, kids: true },
      { key: "taronga", title: "Taronga Zoo", description: "Koalas and kangaroos with harbour views.", cats: ["family", "nature"], slot: "morning", hrs: 4, cost: 50, area: "Mosman", bookable: true, kids: true },
      { key: "botanic", title: "Royal Botanic Garden and Mrs Macquarie's Chair", description: "Gardens with the classic Opera House photo.", cats: ["nature", "relaxation"], slot: "afternoon", hrs: 2, cost: 0, area: "CBD", kids: true },
      { key: "fish-market", title: "Sydney Fish Market", description: "Oysters and sashimi at the waterfront.", cats: ["food"], slot: "morning", hrs: 1.5, cost: 30, area: "Pyrmont", kids: true },
      { key: "surf-lesson", title: "Surf lesson at Bondi", description: "Learn to stand up on Australia's most famous beach.", cats: ["adventure"], slot: "morning", hrs: 2, cost: 80, area: "Bondi", bookable: true },
      { key: "opera-show", title: "Show at the Opera House", description: "Opera, ballet or a concert under the sails.", cats: ["culture", "nightlife"], slot: "evening", hrs: 3, cost: 120, area: "Circular Quay", bookable: true },
      { key: "newtown", title: "Newtown pubs and live music", description: "Sydney's bohemian inner west.", cats: ["nightlife", "food"], slot: "evening", hrs: 3, cost: 35, area: "Newtown" },
    ],
  },
];
