/**
 * Promote a reviewed draft into the live catalog.
 *
 *   node --experimental-strip-types scripts/promote-destination.ts porto
 *
 * Validates catalog-drafts/<slug>.json, writes src/data/destinations/<slug>.ts and
 * regenerates src/data/destinations/index.ts.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { catalogIssues, DestinationSchema } from "../src/lib/catalog-schema.ts";

const DIR = "src/data/destinations";

function main() {
  const slug = process.argv[2];
  if (!slug) throw new Error("Usage: promote-destination.ts <slug>");
  const file = `catalog-drafts/${slug}.json`;
  if (!existsSync(file)) throw new Error(`No draft at ${file}`);
  const draft = JSON.parse(readFileSync(file, "utf8"));
  const parsed = DestinationSchema.safeParse(draft.entry);
  if (!parsed.success) throw new Error(`Draft is invalid:\n${parsed.error.issues.map((i) => `- ${i.path.join(".")}: ${i.message}`).join("\n")}`);
  const issues = catalogIssues(parsed.data);
  if (issues.length) throw new Error(`Fix these before promoting:\n- ${issues.join("\n- ")}`);

  const ident = slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  writeFileSync(
    `${DIR}/${slug}.ts`,
    `// Promoted from catalog-drafts/${slug}.json on ${new Date().toISOString().slice(0, 10)} after human review.\nimport type { Destination } from "../../lib/destinations.ts";\n\nexport const ${ident}: Destination = ${JSON.stringify(parsed.data, null, 2)};\n`,
  );

  const files = readdirSync(DIR).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();
  const idents = files.map((f) => f.replace(/\.ts$/, "")).map((s) => [s, s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())] as const);
  writeFileSync(
    `${DIR}/index.ts`,
    `// Generated by scripts/promote-destination.ts. Do not edit by hand.\nimport type { Destination } from "../../lib/destinations.ts";\n${idents.map(([f, i]) => `import { ${i} } from "./${f}.ts";`).join("\n")}\n\nexport const PROMOTED_DESTINATIONS: Destination[] = [${idents.map(([, i]) => i).join(", ")}];\n`,
  );
  console.log(`Promoted ${slug}. Run npm test to re-check the catalog.`);
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
